### ISSUE TITLE
有的时候TileMap导入失败怎么办

### ISSUE THREAD

**Issue by ZLUO33** [dasasdhba/Mario_Forever_Berry_Editor#3]
![image](https://user-images.githubusercontent.com/36525348/183343424-12afc2cc-b6d4-4608-b502-991055be8f2f.png)
![image](https://user-images.githubusercontent.com/36525348/183343473-a7839057-8f5b-42f7-9e90-c2b21c527b8a.png)
马里奥一进入选关画面就掉下去了【

**Comment by dasasdhba** [comment]
好像是 godot 的问题，或者说你清空了原本的 tileset？？

**Comment by Lazy-Rabbit-2001** [comment]
可能是你把tile贴图给误删了？
因为报错是!get_texture().is_valid()为真，说明获取的贴图非法
有可能是你删了，系统它找不到；亦或是你那个texture有别的问题
不过我觉得前者的概率会更大一点

**Comment by ZLUO33** [comment]
我用的DownloadZIP下载，解压下来什么都没动就这样了

**Comment by ZLUO33** [comment]
好像把杀毒软件关了然后点一下项目/重新加载当前项目就行了【
